### ISSUE TITLE
Magic Numbers

### ISSUE THREAD

**Issue by westwoods** [AA-B1-3Team/VideoRental#11]
https://github.com/AA-B1-3Team/VideoRental/blob/83217b1ee45c796e36717900e6638d6d2e46a043/Video.java#L11-L13

int 말고 enum으로 추출 필요

**Comment by kost0806** [comment]
https://github.com/AA-B1-3Team/VideoRental/commit/0f0945d1da0b6371fa9b89ee29b69fd9bd715d2e
Enum Class로 추출 완료
