### ISSUE TITLE
Lack of Encapsulation

### ISSUE THREAD

**Issue by westwoods** [AA-B1-3Team/VideoRental#13]
https://github.com/AA-B1-3Team/VideoRental/blob/83217b1ee45c796e36717900e6638d6d2e46a043/Video.java#L18-L23

생성자에서만 사용하는 setter함수가 public으로 노출됨

**Comment by eastskim48** [comment]
f0701c19ca40287ab30323175cfbdfbcb9289bd8 에서 setter함수를 private으로 수정하여 해결했습니다.
