### ISSUE TITLE
Long Method

### ISSUE THREAD

**Issue by hangoby** [AA-B1-3Team/VideoRental#14]
https://github.com/AA-B1-3Team/VideoRental/blob/83217b1ee45c796e36717900e6638d6d2e46a043/Customer.java#L35-L36

public String getReport() { 
60줄짜리 함수,

1-2 반복 후 3. 프린트
1. 비디오 빌린 날짜 확인
2.  빌린 날짜 * 비용
3.프린트

**Comment by westwoods** [comment]
https://github.com/AA-B1-3Team/VideoRental/commit/ae474e5c52b219c9cf203132bb05172603063d83 로 수정완료.
