### ISSUE TITLE
Long Method

### ISSUE THREAD

**Issue by kost0806** [AA-B1-3Team/VideoRental#17]
https://github.com/AA-B1-3Team/VideoRental/blob/83217b1ee45c796e36717900e6638d6d2e46a043/VRUI.java#L149-L182

`Customer`를 찾는 로직과 `Video`를 찾는 로직이 별도 Method로 분리되는게 바람직해 보임

**Comment by kost0806** [comment]
#4 와 다르게 Medium인 이유: 
- #4 가 수정되면 같이 어느정도 수정이 되기에 Medium으로  지정

**Comment by eastskim48** [comment]
https://github.com/AA-B1-3Team/VideoRental/commit/3a66291b27794810de3e272515f417d44129ca8b `Video`를 찾는 로직 `VideoController`의 `register` Method로 분리했습니다
