### ISSUE TITLE
Larger class

### ISSUE THREAD

**Issue by kost0806** [AA-B1-3Team/VideoRental#2]
https://github.com/AA-B1-3Team/VideoRental/blob/83217b1ee45c796e36717900e6638d6d2e46a043/VRUI.java#L6

**Comment by kost0806** [comment]
002e64b2 VRUI의 Business Logic을 CustomerController와 VideoController로 이동
https://github.com/AA-B1-3Team/VideoRental/commit/72a96c4df579e9283d07845cee49fc5ea15578ff Rental 책임을 CustomerController로 이동

**Comment by eastskim48** [comment]
3a66291b27794810de3e272515f417d44129ca8b Video를 Register하는 책임을 VideoController로 이동

**Comment by kost0806** [comment]
https://github.com/AA-B1-3Team/VideoRental/commit/190baff6fb3d44b7676dcbe670d7a7a4a582b78e register까지 분리 완료로 Class 책임 분리 완료
