### ISSUE TITLE
Extract Method

### ISSUE THREAD

**Issue by hangoby** [AA-B1-3Team/VideoRental#20]
https://github.com/AA-B1-3Team/VideoRental/blob/83217b1ee45c796e36717900e6638d6d2e46a043/Customer.java#L86-L91

print함수를 별도로???

**Comment by westwoods** [comment]
이 부분 모호한 if문도 있어 보이는데요. 적당한 code smell을 못찾았어요..  error 에 가까운거같아요.
```
if ( totalPoint >= 10 ) { 
 	System.out.println("Congrat! You earned one free coupon"); 
} 
eles if ( totalPoint >= 30 ) { 
 	System.out.println("Congrat! You earned two free coupon"); 
} 
```

**Comment by westwoods** [comment]
https://github.com/AA-B1-3Team/VideoRental/issues/20 [Extract Method](https://github.com/AA-B1-3Team/VideoRental/pull/25/commits/ae474e5c52b219c9cf203132bb05172603063d83) 에서 해결하였습니다.
