### ISSUE TITLE
Code duplication 

### ISSUE THREAD

**Issue by westwoods** [AA-B1-3Team/VideoRental#4]
https://github.com/AA-B1-3Team/VideoRental/blob/83217b1ee45c796e36717900e6638d6d2e46a043/VRUI.java#L37-L46

L64, L130 L150에 반복됨, getCustomer등의 함수로 추출해야 함

**Comment by kost0806** [comment]
#17 와 연관있는 Code Smell 같습니다!

**Comment by kost0806** [comment]
https://github.com/AA-B1-3Team/VideoRental/commit/117def3c7457fc81f2ed4e0864a097bb4ffb9d0e
로 수정 완료했습니다!
